version: '3.8'
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=traderuser
      - MONGO_INITDB_ROOT_PASSWORD=traderpassword
    ports:
      - '5000:27017'
    volumes:
      - ./trader-mongodb-data:/data/db
