# fly.toml file generated for hanseaticmonitor on 2022-05-09T21:47:42+02:00

app = "hanseaticmonitor"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT=3000

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  tcp_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
