import { IChat, IGame, ISession } from '../../../shared/types';
import { getHexesWithinRangeOf } from './getHexesWithinRangeOf';

export const MOCK_SESSIONS: ISession[] = [
  {
    user: { name: 'lynden', uuid: '1UiCjICtBFvRPSVb2cTAP', connected: true },
    activeGameUuid: 'dDV7I0PZkSX1SdDCILTkA',
    // activeGameUuid: 'VJHXkcSEtfpT01yhgNxB0',
    // activeGameUuid: 'T37rB8x5iolLlYmReFZix',
    uuid: 'Tl-3NLoZNVOGGZMNInRz8',
    email: 'iphonelynden@gmail.com',
  },
  {
    user: { name: 'person1', uuid: '4s1zxMT_G5DsCnP5GRk7l', connected: true },
    activeGameUuid: 'dDV7I0PZkSX1SdDCILTkA',
    // activeGameUuid: 'VJHXkcSEtfpT01yhgNxB0',
    // activeGameUuid: 'T37rB8x5iolLlYmReFZix',
    uuid: 'ul0BTmoadsDeBo1yKysKb',
    email: 'person1@mock.now',
  },
];

export const MOCK_CHAT: IChat = {
  gameUuid: 'dDV7I0PZkSX1SdDCILTkA',
  messages: [
    {
      uuid: '0syDyCcqbi9f2Xhnx7PzS',
      from: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been',
    },
    {
      uuid: '78n7n4At3seZJ3DSeHLZy',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been',
    },
    {
      uuid: '2lJeKY38O5Gion6pGPoPr',
      from: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      message:
        'lly unchanged. It was popularised in the 1960s with the release of Letraset sheets conta',
    },
    {
      uuid: 'Gb1Y-IdzB-Y4tvOThwCPV',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'Use setTimeout in your React components to execute a function or block of code after a period of time. Let’s explore ho',
    },
    {
      uuid: '3iAUyNQ6PzLwvBhNvWwSY',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'For example, the code below prints “Hello, World!” to the developer console after 3,000 milliseconds (or 3 seconds).',
    },
    {
      uuid: 'VUrYqPDVC9dV6TJ3Hn0TC',
      from: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      message:
        'It is a long established fact that a reader will be distracted by the readable content of a pa',
    },
    {
      uuid: 'KAlgBRi7lwqahhbwogvZa',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'tTimeout inside of the useEffect Hook, which is the equivalent of the componentDidMount lifecycle method in Class components',
    },
  ],
};

export const MOCK_GAME: IGame = {
  name: 'lyndens game',
  uuid: 'dDV7I0PZkSX1SdDCILTkA',
  numberOfCitiesToEmpty: 8,
  isRanked: true,
  tempo: 10 * 60 * 1000,
  achievements: [
    {
      name: 'Banker',
      uuid: 'Banker_A_2-5_4P',
      description: 'Four contracts worth 3 VP',
      value: 4,
      target: 4,
    },
    {
      name: 'Merchant',
      uuid: 'Merchant_A_2-3_5P',
      description: 'Six contracts worth 1 VP',
      value: 5,
      target: 6,
    },
    {
      name: 'Diversifier',
      uuid: 'Diversifier_B_2-5_4P',
      description: 'Two red, yellow, gray cargo',
      value: 4,
      target: 6,
    },
    {
      name: 'Supplier',
      uuid: 'Supplier_A_2-3_4P',
      description: 'Three emptied cities',
      value: 4,
      target: 3,
    },
    {
      name: 'Specialist',
      uuid: 'Specialist_B_2-5_4P',
      description: 'Four green contracts',
      value: 4,
      target: 4,
    },
  ],
  startTime: new Date().getTime(),
  endTime: 0,
  players: [
    {
      color: 'black',
      user: { name: 'lynden', uuid: '1UiCjICtBFvRPSVb2cTAP', connected: true },
      hasMadeEndGameMove: false,
      contractsFulfilled: [
        {
          value: 2,
          cargo: ['yellow', 'brown'],
          region: 'East',
          uuid: 'E_yel_bro_2',
        },
        {
          value: 1,
          cargo: ['gray', 'blue'],
          region: 'East',
          uuid: 'E_gry_blu_1',
        },
        {
          value: 1,
          cargo: ['gray', 'brown'],
          region: 'East',
          uuid: 'E_gry_bro_1',
        },
        {
          value: 2,
          cargo: ['yellow', 'gray'],
          region: 'Central',
          uuid: 'C_yel_gry_2',
        },
        {
          value: 2,
          cargo: ['green', 'black'],
          region: 'East',
          uuid: 'E_grn_bla_2',
        },
        {
          value: 2,
          cargo: ['yellow', 'black'],
          region: 'East',
          uuid: 'E_yel_bla_2',
        },
        {
          value: 1,
          cargo: ['green', 'black'],
          region: 'Central',
          uuid: 'C_grn_bla_1',
        },
        {
          value: 2,
          cargo: ['yellow', 'gray'],
          region: 'East',
          uuid: 'E_yel_gry_2',
        },
        {
          value: 2,
          cargo: ['gray', 'blue'],
          region: 'Central',
          uuid: 'C_gry_blu_2',
        },
        {
          value: 2,
          cargo: ['gray', 'black'],
          region: 'Central',
          uuid: 'C_gry_bla_2',
        },
        {
          value: 3,
          cargo: ['yellow', 'blue'],
          region: 'West',
          uuid: 'W_yel_blu_3',
        },
        {
          value: 3,
          cargo: ['red', 'gray'],
          region: 'East',
          uuid: 'E_red_gry_3',
        },
        {
          value: 2,
          cargo: ['green', 'brown'],
          region: 'East',
          uuid: 'E_grn_bro_2',
        },
        {
          value: 3,
          cargo: ['gray', 'brown'],
          region: 'West',
          uuid: 'W_gry_bro_3',
        },
        {
          value: 5,
          cargo: ['gray', 'blue'],
          region: 'West',
          uuid: 'W_gry_blu_5',
        },
        {
          value: 3,
          cargo: ['red', 'gray'],
          region: 'West',
          uuid: 'W_red_gry_3',
        },
      ],
      citiesEmptied: [
        { name: 'Riga', value: 2 },
        { name: 'Tønsberg', value: 2 },
        { name: 'Brügge', value: 2 },
        { name: 'Bergen', value: 2 },
      ],
      achievements: [],
      achievementsProgress: [
        {
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          achievedTargets: { contracts: [] },
          targetType: 'contract',
        },
        {
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          achievedTargets: { contracts: [] },
          targetType: 'contract',
        },
        {
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 0,
          achievedTargets: { cargo: [] },
          targetType: 'cargo',
        },
        {
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          achievedTargets: { cities: [] },
          targetType: 'city',
        },
        {
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          achievedTargets: { contracts: [] },
          targetType: 'contract',
        },
      ],
      position: { column: 8, row: 5 },
      victoryPoints: 47,
      cargo: ['black', 'blue', 'yellow', 'black', 'black'],
      hasTimedOut: false,
      timeLeft: 3 * 60 * 1000,
      timedOutRound: 0,
    },
    {
      color: 'blue',
      user: { name: 'person1', uuid: '4s1zxMT_G5DsCnP5GRk7l', connected: true },
      hasMadeEndGameMove: false,
      contractsFulfilled: [
        {
          value: 3,
          cargo: ['yellow', 'green'],
          region: 'East',
          uuid: 'E_yel_grn_3',
        },
        {
          value: 2,
          cargo: ['yellow', 'brown'],
          region: 'Central',
          uuid: 'C_yel_bro_2',
        },
        {
          value: 2,
          cargo: ['blue', 'brown'],
          region: 'Central',
          uuid: 'C_blu_bro_2',
        },
        {
          value: 1,
          cargo: ['brown', 'black'],
          region: 'West',
          uuid: 'W_bro_bla_1',
        },
        {
          value: 2,
          cargo: ['yellow', 'brown'],
          region: 'West',
          uuid: 'W_yel_bro_2',
        },
        {
          value: 1,
          cargo: ['red', 'green'],
          region: 'West',
          uuid: 'W_red_grn_1',
        },
        {
          value: 1,
          cargo: ['green', 'black'],
          region: 'West',
          uuid: 'W_grn_bla_1',
        },
        {
          value: 2,
          cargo: ['blue', 'brown'],
          region: 'West',
          uuid: 'W_blu_bro_2',
        },
        {
          value: 3,
          cargo: ['red', 'black'],
          region: 'East',
          uuid: 'E_red_bla_3',
        },
        {
          value: 2,
          cargo: ['gray', 'green'],
          region: 'East',
          uuid: 'E_gry_grn_2',
        },
        {
          value: 3,
          cargo: ['gray', 'brown'],
          region: 'Central',
          uuid: 'C_gry_bro_3',
        },
        {
          value: 2,
          cargo: ['blue', 'black'],
          region: 'West',
          uuid: 'W_blu_bla_2',
        },
        {
          value: 3,
          cargo: ['red', 'blue'],
          region: 'East',
          uuid: 'E_red_blu_3',
        },
        {
          value: 5,
          cargo: ['red', 'yellow'],
          region: 'East',
          uuid: 'E_red_yel_5',
        },
        {
          value: 3,
          cargo: ['gray', 'black'],
          region: 'West',
          uuid: 'W_gry_bla_3',
        },
        {
          value: 5,
          cargo: ['yellow', 'gray'],
          region: 'West',
          uuid: 'W_yel_gry_5',
        },
        {
          value: 3,
          cargo: ['gray', 'green'],
          region: 'West',
          uuid: 'W_gry_grn_3',
        },
        {
          value: 2,
          cargo: ['yellow', 'green'],
          region: 'West',
          uuid: 'W_yel_grn_2',
        },
        {
          value: 2,
          cargo: ['red', 'black'],
          region: 'Central',
          uuid: 'C_red_bla_2',
        },
      ],
      citiesEmptied: [
        { name: 'Åbo', value: 2 },
        { name: 'Newcastle', value: 2 },
        { name: 'London', value: 2 },
        { name: 'Hamburg', value: 2 },
        { name: 'Stettin', value: 2 },
      ],
      achievements: [],
      achievementsProgress: [
        {
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          achievedTargets: { contracts: [] },
          targetType: 'contract',
        },
        {
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          achievedTargets: { contracts: [] },
          targetType: 'contract',
        },
        {
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 0,
          achievedTargets: { cargo: [] },
          targetType: 'cargo',
        },
        {
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          achievedTargets: { cities: [] },
          targetType: 'city',
        },
        {
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          achievedTargets: { contracts: [] },
          targetType: 'contract',
        },
      ],
      position: { column: 6, row: 7 },
      victoryPoints: 59,
      cargo: ['green', 'red', 'yellow', 'blue'],
      hasTimedOut: false,
      timeLeft: 3 * 60 * 1000,
      timedOutRound: 0,
    },
  ],
  board: [
    {
      column: 0,
      row: 3,
      city: {
        name: 'Newcastle',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['black', 'red'],
        region: 'West',
      },
    },
    { column: 1, row: 2 },
    { column: 1, row: 4 },
    { column: 1, row: 6 },
    {
      column: 1,
      row: 8,
      city: {
        name: 'London',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['red', 'red'],
        region: 'West',
      },
    },
    { column: 2, row: 1 },
    { column: 2, row: 3 },
    { column: 2, row: 5 },
    {
      column: 2,
      row: 7,
      city: {
        name: 'Brügge',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['brown', 'brown'],
        region: 'West',
      },
    },
    {
      column: 3,
      row: 0,
      city: {
        name: 'Bergen',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['green', 'green'],
        region: 'West',
      },
    },
    { column: 3, row: 2 },
    { column: 3, row: 4 },
    {
      column: 3,
      row: 6,
      city: {
        name: 'Hamburg',
        nrContracts: 3,
        contracts: [
          {
            value: 2,
            cargo: ['green', 'blue'],
            region: 'West',
            uuid: 'W_grn_blu_2',
          },
        ],
        coatOfArms: '',
        goods: ['green', 'brown'],
        region: 'West',
      },
    },
    { column: 4, row: 1 },
    {
      column: 5,
      row: 0,
      city: {
        name: 'Tønsberg',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['blue'],
        region: 'Central',
      },
    },
    { column: 5, row: 2 },
    { column: 5, row: 4 },
    {
      column: 5,
      row: 6,
      city: {
        name: 'Lübeck',
        nrContracts: 3,
        contracts: [
          {
            value: 2,
            cargo: ['red', 'blue'],
            region: 'Central',
            uuid: 'C_red_blu_2',
          },
          {
            value: 2,
            cargo: ['brown', 'black'],
            region: 'Central',
            uuid: 'C_bro_bla_2',
          },
        ],
        coatOfArms: '',
        goods: ['yellow', 'yellow'],
        region: 'Central',
      },
    },
    {
      column: 6,
      row: 5,
      city: {
        name: 'Falsterbo',
        nrContracts: 3,
        contracts: [
          {
            value: 5,
            cargo: ['red', 'gray'],
            region: 'Central',
            uuid: 'C_red_gry_5',
          },
        ],
        coatOfArms: '',
        goods: ['black'],
        region: 'Central',
      },
    },
    {
      column: 6,
      row: 7,
      city: {
        name: 'Stettin',
        nrContracts: 3,
        contracts: [
          {
            value: 1,
            cargo: ['green', 'blue'],
            region: 'Central',
            uuid: 'C_grn_blu_1',
          },
        ],
        coatOfArms: '',
        goods: ['green', 'yellow'],
        region: 'Central',
      },
    },
    { column: 7, row: 4 },
    { column: 7, row: 6 },
    {
      column: 8,
      row: 1,
      city: {
        name: 'Stockholm',
        nrContracts: 3,
        contracts: [
          {
            value: 2,
            cargo: ['green', 'blue'],
            region: 'East',
            uuid: 'E_grn_blu_2',
          },
        ],
        coatOfArms: '',
        goods: ['blue', 'brown'],
        region: 'East',
      },
    },
    {
      column: 8,
      row: 3,
      city: {
        name: 'Visby',
        nrContracts: 4,
        contracts: [
          {
            value: 2,
            cargo: ['yellow', 'blue'],
            region: 'East',
            uuid: 'E_yel_blu_2',
          },
        ],
        coatOfArms: '',
        goods: ['gray', 'black'],
        region: 'East',
      },
    },
    {
      column: 8,
      row: 5,
      city: {
        name: 'Danzig',
        nrContracts: 3,
        contracts: [
          {
            value: 1,
            cargo: ['blue', 'black'],
            region: 'East',
            uuid: 'E_blu_bla_1',
          },
          {
            value: 2,
            cargo: ['yellow', 'brown'],
            region: 'East',
            uuid: 'E_yel_bro_2',
          },
          {
            value: 2,
            cargo: ['yellow', 'black'],
            region: 'East',
            uuid: 'E_yel_bla_2',
          },
        ],
        coatOfArms: '',
        goods: ['black', 'brown'],
        region: 'East',
      },
    },
    {
      column: 9,
      row: 0,
      city: {
        name: 'Åbo',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['black', 'black'],
        region: 'East',
      },
    },
    { column: 9, row: 2 },
    { column: 9, row: 4 },
    { column: 10, row: 1 },
    {
      column: 10,
      row: 3,
      city: {
        name: 'Riga',
        nrContracts: 3,
        contracts: [],
        coatOfArms: '',
        goods: ['blue', 'blue'],
        region: 'East',
      },
    },
    {
      column: 11,
      row: 0,
      city: {
        name: 'Reval',
        nrContracts: 3,
        contracts: [
          {
            value: 3,
            cargo: ['red', 'brown'],
            region: 'East',
            uuid: 'E_red_bro_3',
          },
        ],
        coatOfArms: '',
        goods: ['gray', 'gray'],
        region: 'East',
      },
    },
  ],
  state: {
    currentRound: {
      playerUuid: '4s1zxMT_G5DsCnP5GRk7l',
      movesLeft: 1,
      movesAvailable: ['sail', 'load'],
      achievementsEarned: [],
      hexesWithinRange: [
        { row: 6, column: 5 },
        { row: 5, column: 6 },
        { row: 6, column: 7 },
        { row: 4, column: 5 },
        { row: 7, column: 6 },
        { row: 4, column: 7 },
        { row: 5, column: 8 },
        { row: 2, column: 5 },
        { row: 3, column: 8 },
        { row: 4, column: 9 },
      ],
      startTime: new Date().getTime(),
    },
    round: 100,
    status: 'playing',
    numberOfCitiesEmptied: 7,
  },
};

export const MOCK_GAME_ACHIEVEMENTS: IGame = {
  state: {
    currentRound: {
      playerUuid: '4s1zxMT_G5DsCnP5GRk7l',
      movesLeft: 2,
      movesAvailable: ['load', 'sail', 'trade'],
      hexesWithinRange: [
        {
          row: 4,
          column: 5,
        },
        {
          row: 5,
          column: 6,
        },
        {
          row: 7,
          column: 6,
        },
        {
          row: 2,
          column: 5,
        },
        {
          row: 6,
          column: 5,
        },
        {
          row: 4,
          column: 7,
        },
        {
          row: 6,
          column: 7,
        },
        {
          row: 1,
          column: 4,
        },
        {
          row: 0,
          column: 5,
        },
        {
          row: 3,
          column: 8,
        },
        {
          row: 5,
          column: 8,
        },
      ],
      achievementsEarned: [],
      startTime: new Date().getTime(),
    },
    status: 'playing',
    round: 2,
    numberOfCitiesEmptied: 0,
  },
  name: 'LyndenTest',
  uuid: 'iX1JUcNFe5mEQ3igWXdUL',
  startTime: new Date().getTime(),
  endTime: 0,
  isRanked: false,
  players: [
    {
      user: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      position: {
        column: 8,
        row: 3,
      },
      color: 'black',
      contractsFulfilled: [
        {
          value: 1,
          cargo: ['yellow', 'brown'],
          region: 'East',
          uuid: 'E_yel_bro_1',
        },
        {
          value: 5,
          cargo: ['red', 'green'],
          region: 'East',
          uuid: 'E_red_grn_5',
        },
        {
          value: 2,
          cargo: ['green', 'black'],
          region: 'East',
          uuid: 'E_grn_bla_2',
        },
        {
          value: 2,
          cargo: ['yellow', 'gray'],
          region: 'Central',
          uuid: 'C_yel_gry_2',
        },
        {
          value: 1,
          cargo: ['green', 'black'],
          region: 'Central',
          uuid: 'C_grn_bla_1',
        },
        {
          value: 2,
          cargo: ['red', 'black'],
          region: 'Central',
          uuid: 'C_red_bla_2',
        },
        {
          value: 2,
          cargo: ['yellow', 'brown'],
          region: 'West',
          uuid: 'W_yel_bro_2',
        },
        {
          value: 3,
          cargo: ['gray', 'brown'],
          region: 'West',
          uuid: 'W_gry_bro_3',
        },
        {
          value: 1,
          cargo: ['red', 'brown'],
          region: 'West',
          uuid: 'W_red_bro_1',
        },
      ],
      citiesEmptied: [
        { name: 'Riga', value: 2 },
        { name: 'Tønsberg', value: 2 },
        { name: 'Brügge', value: 2 },
      ],
      achievements: [],
      achievementsProgress: [
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_B_2-3_4P',
          target: 7,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_4-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['blue', 'brown'],
                region: 'East',
                uuid: 'E_blu_bro_2',
              },
              {
                value: 2,
                cargo: ['yellow', 'blue'],
                region: 'East',
                uuid: 'E_yel_blu_2',
              },
              {
                value: 2,
                cargo: ['red', 'black'],
                region: 'West',
                uuid: 'W_red_bla_2',
              },
              {
                value: 2,
                cargo: ['blue', 'black'],
                region: 'West',
                uuid: 'W_blu_bla_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_B_4-5_4P',
          target: 6,
          progress: 4,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [
              'red',
              'red',
              'yellow',
              'gray',
              'green',
              'blue',
              'blue',
              'blue',
              'blue',
              'brown',
              'black',
              'black',
            ],
          },
          uuid: 'Diversifier_A_2-5_4P',
          target: 7,
          progress: 7,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: ['red', 'red', 'yellow', 'gray'],
          },
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 4,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'Åbo',
                value: 2,
              },
              {
                name: 'Newcastle',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'Åbo',
                value: 2,
              },
              {
                name: 'Newcastle',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_A_2-3_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_B_4-5_3P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['blue', 'brown'],
                region: 'East',
                uuid: 'E_blu_bro_2',
              },
              {
                value: 2,
                cargo: ['yellow', 'blue'],
                region: 'East',
                uuid: 'E_yel_blu_2',
              },
              {
                value: 3,
                cargo: ['green', 'blue'],
                region: 'West',
                uuid: 'W_grn_blu_3',
              },
              {
                value: 2,
                cargo: ['blue', 'black'],
                region: 'West',
                uuid: 'W_blu_bla_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Specialist_A_2-5_3P',
          target: 3,
          progress: 4,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_A_2-5_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_A_2-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_B_2-5_3P',
          target: 3,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
      ],
      victoryPoints: 0,
      cargo: ['gray', 'black'],
      hasMadeEndGameMove: false,
      hasTimedOut: false,
      timeLeft: 3479450,
      timedOutRound: 0,
    },
    {
      user: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      position: {
        column: 5,
        row: 6,
      },
      color: 'blue',
      contractsFulfilled: [
        {
          value: 4,
          cargo: ['red', 'gray'],
          region: 'East',
          uuid: 'E_red_gry_4',
        },
        {
          value: 2,
          cargo: ['blue', 'brown'],
          region: 'East',
          uuid: 'E_blu_bro_2',
        },
        {
          value: 2,
          cargo: ['yellow', 'blue'],
          region: 'East',
          uuid: 'E_yel_blu_2',
        },
        {
          value: 3,
          cargo: ['green', 'blue'],
          region: 'West',
          uuid: 'W_grn_blu_3',
        },
        {
          value: 2,
          cargo: ['red', 'black'],
          region: 'West',
          uuid: 'W_red_bla_2',
        },
        {
          value: 2,
          cargo: ['blue', 'black'],
          region: 'West',
          uuid: 'W_blu_bla_2',
        },
      ],
      citiesEmptied: [
        { name: 'Åbo', value: 2 },
        { name: 'Newcastle', value: 2 },
      ],
      achievements: [],
      achievementsProgress: [
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_B_2-3_4P',
          target: 7,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_4-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['blue', 'brown'],
                region: 'East',
                uuid: 'E_blu_bro_2',
              },
              {
                value: 2,
                cargo: ['yellow', 'blue'],
                region: 'East',
                uuid: 'E_yel_blu_2',
              },
              {
                value: 2,
                cargo: ['red', 'black'],
                region: 'West',
                uuid: 'W_red_bla_2',
              },
              {
                value: 2,
                cargo: ['blue', 'black'],
                region: 'West',
                uuid: 'W_blu_bla_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_B_4-5_4P',
          target: 6,
          progress: 4,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [
              'red',
              'red',
              'yellow',
              'gray',
              'green',
              'blue',
              'blue',
              'blue',
              'blue',
              'brown',
              'black',
              'black',
            ],
          },
          uuid: 'Diversifier_A_2-5_4P',
          target: 7,
          progress: 7,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: ['red', 'red', 'yellow', 'gray'],
          },
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 4,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'Åbo',
                value: 2,
              },
              {
                name: 'Newcastle',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'Åbo',
                value: 2,
              },
              {
                name: 'Newcastle',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_A_2-3_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_B_4-5_3P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['blue', 'brown'],
                region: 'East',
                uuid: 'E_blu_bro_2',
              },
              {
                value: 2,
                cargo: ['yellow', 'blue'],
                region: 'East',
                uuid: 'E_yel_blu_2',
              },
              {
                value: 3,
                cargo: ['green', 'blue'],
                region: 'West',
                uuid: 'W_grn_blu_3',
              },
              {
                value: 2,
                cargo: ['blue', 'black'],
                region: 'West',
                uuid: 'W_blu_bla_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Specialist_A_2-5_3P',
          target: 3,
          progress: 4,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_A_2-5_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_A_2-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_B_2-5_3P',
          target: 3,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
      ],
      victoryPoints: 0,
      cargo: ['yellow'],
      hasMadeEndGameMove: false,
      hasTimedOut: false,
      timeLeft: 3577083,
      timedOutRound: 0,
    },
    {
      user: {
        name: 'Person2',
        uuid: '8YNzwnOSPAAEAwK9bHdYy',
        connected: true,
      },
      position: {
        column: 5,
        row: 6,
      },
      color: 'yellow',
      contractsFulfilled: [
        {
          value: 5,
          cargo: ['gray', 'blue'],
          region: 'West',
          uuid: 'W_gry_blu_5',
        },
        {
          value: 2,
          cargo: ['yellow', 'black'],
          region: 'West',
          uuid: 'W_yel_bla_2',
        },
        {
          value: 5,
          cargo: ['yellow', 'gray'],
          region: 'West',
          uuid: 'W_yel_gry_5',
        },
        {
          value: 2,
          cargo: ['brown', 'black'],
          region: 'West',
          uuid: 'W_bro_bla_2',
        },
        {
          value: 1,
          cargo: ['red', 'green'],
          region: 'West',
          uuid: 'W_red_grn_1',
        },
        {
          value: 1,
          cargo: ['green', 'black'],
          region: 'West',
          uuid: 'W_grn_bla_1',
        },
      ],
      citiesEmptied: [
        { name: 'London', value: 2 },
        { name: 'Bergen', value: 2 },
      ],
      achievements: [],
      achievementsProgress: [
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_B_2-3_4P',
          target: 7,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 1,
                cargo: ['red', 'green'],
                region: 'West',
                uuid: 'W_red_grn_1',
              },
              {
                value: 1,
                cargo: ['green', 'black'],
                region: 'West',
                uuid: 'W_grn_bla_1',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_A_4-5_5P',
          target: 5,
          progress: 2,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['yellow', 'black'],
                region: 'West',
                uuid: 'W_yel_bla_2',
              },
              {
                value: 2,
                cargo: ['brown', 'black'],
                region: 'West',
                uuid: 'W_bro_bla_2',
              },
              {
                value: 1,
                cargo: ['red', 'green'],
                region: 'West',
                uuid: 'W_red_grn_1',
              },
              {
                value: 1,
                cargo: ['green', 'black'],
                region: 'West',
                uuid: 'W_grn_bla_1',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_B_4-5_4P',
          target: 6,
          progress: 4,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Diversifier_A_2-5_4P',
          target: 7,
          progress: 0,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: ['red', 'yellow', 'yellow', 'gray', 'gray'],
          },
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 5,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'London',
                value: 2,
              },
              {
                name: 'Bergen',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'London',
                value: 2,
              },
              {
                name: 'Bergen',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_A_2-3_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_B_4-5_3P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 5,
                cargo: ['gray', 'blue'],
                region: 'West',
                uuid: 'W_gry_blu_5',
              },
            ],
            cargo: [],
          },
          uuid: 'Specialist_A_2-5_3P',
          target: 3,
          progress: 1,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_A_2-5_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_A_2-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_B_2-5_3P',
          target: 3,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
      ],
      victoryPoints: 0,
      cargo: ['yellow'],
      hasMadeEndGameMove: false,
      hasTimedOut: false,
      timeLeft: 3577083,
      timedOutRound: 0,
    },
    {
      user: { name: 'Person4', uuid: 'v87ki0VQLVv23RCuUZY77', connected: true },
      position: {
        column: 5,
        row: 6,
      },
      color: 'red',
      contractsFulfilled: [
        {
          value: 3,
          cargo: ['gray', 'blue'],
          region: 'Central',
          uuid: 'C_gry_blu_3',
        },
        {
          value: 7,
          cargo: ['red', 'gray'],
          region: 'Central',
          uuid: 'C_red_gry_7',
        },
        {
          value: 3,
          cargo: ['red', 'brown'],
          region: 'Central',
          uuid: 'C_red_bro_3',
        },
        {
          value: 2,
          cargo: ['red', 'blue'],
          region: 'Central',
          uuid: 'C_red_blu_2',
        },
        {
          value: 1,
          cargo: ['yellow', 'black'],
          region: 'Central',
          uuid: 'C_yel_bla_1',
        },
        {
          value: 2,
          cargo: ['gray', 'green'],
          region: 'Central',
          uuid: 'C_gry_grn_2',
        },
      ],
      citiesEmptied: [
        { name: 'Lübeck', value: 2 },
        { name: 'Falsterbo', value: 2 },
      ],
      achievements: [],
      achievementsProgress: [
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_B_2-3_4P',
          target: 7,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 1,
                cargo: ['yellow', 'black'],
                region: 'Central',
                uuid: 'C_yel_bla_1',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_A_4-5_5P',
          target: 5,
          progress: 1,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['red', 'blue'],
                region: 'Central',
                uuid: 'C_red_blu_2',
              },
              {
                value: 1,
                cargo: ['yellow', 'black'],
                region: 'Central',
                uuid: 'C_yel_bla_1',
              },
              {
                value: 2,
                cargo: ['gray', 'green'],
                region: 'Central',
                uuid: 'C_gry_grn_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_B_4-5_4P',
          target: 6,
          progress: 3,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Diversifier_A_2-5_4P',
          target: 7,
          progress: 0,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: ['red', 'red', 'red', 'yellow', 'gray', 'gray', 'gray'],
          },
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 5,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [
              {
                name: 'Lübeck',
                value: 2,
              },
              {
                name: 'Falsterbo',
                value: 2,
              },
            ],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 2,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_A_2-3_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_B_4-5_3P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 3,
                cargo: ['gray', 'blue'],
                region: 'Central',
                uuid: 'C_gry_blu_3',
              },
              {
                value: 2,
                cargo: ['red', 'blue'],
                region: 'Central',
                uuid: 'C_red_blu_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Specialist_A_2-5_3P',
          target: 3,
          progress: 2,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_A_2-5_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_A_2-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_B_2-5_3P',
          target: 3,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
      ],
      victoryPoints: 0,
      cargo: ['yellow'],
      hasMadeEndGameMove: false,
      hasTimedOut: false,
      timeLeft: 3577083,
      timedOutRound: 0,
    },
    {
      user: { name: 'Person3', uuid: 'Vr2LJteMKXN6RAS5Ae8qs', connected: true },
      position: {
        column: 5,
        row: 6,
      },
      color: 'black',
      contractsFulfilled: [
        {
          value: 2,
          cargo: ['green', 'brown'],
          region: 'West',
          uuid: 'W_grn_bro_2',
        },
        {
          value: 2,
          cargo: ['green', 'blue'],
          region: 'West',
          uuid: 'W_grn_blu_2',
        },
        {
          value: 2,
          cargo: ['blue', 'brown'],
          region: 'Central',
          uuid: 'C_blu_bro_2',
        },
      ],
      citiesEmptied: [],
      achievements: [],
      achievementsProgress: [
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_A_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Banker_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_2-3_5P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_B_2-3_4P',
          target: 7,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Merchant_A_4-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['green', 'brown'],
                region: 'West',
                uuid: 'W_grn_bro_2',
              },
              {
                value: 2,
                cargo: ['green', 'blue'],
                region: 'West',
                uuid: 'W_grn_blu_2',
              },
              {
                value: 2,
                cargo: ['blue', 'brown'],
                region: 'Central',
                uuid: 'C_blu_bro_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Merchant_B_4-5_4P',
          target: 6,
          progress: 3,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Diversifier_A_2-5_4P',
          target: 7,
          progress: 0,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Diversifier_B_2-5_4P',
          target: 6,
          progress: 0,
          targetType: 'cargo',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_A_2-3_4P',
          target: 3,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Supplier_B_4-5_3P',
          target: 2,
          progress: 0,
          targetType: 'city',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_A_2-3_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Specialist_B_2-5_4P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Monopolist_B_4-5_3P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [
              {
                value: 2,
                cargo: ['green', 'blue'],
                region: 'West',
                uuid: 'W_grn_blu_2',
              },
              {
                value: 2,
                cargo: ['blue', 'brown'],
                region: 'Central',
                uuid: 'C_blu_bro_2',
              },
            ],
            cargo: [],
          },
          uuid: 'Specialist_A_2-5_3P',
          target: 3,
          progress: 2,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_A_2-5_4P',
          target: 6,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_A_2-5_5P',
          target: 5,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Explorer_B_2-5_3P',
          target: 3,
          progress: 0,
          targetType: 'contract',
        },
        {
          achievedTargets: {
            cities: [],
            contracts: [],
            cargo: [],
          },
          uuid: 'Regional_B_2-5_3P',
          target: 4,
          progress: 0,
          targetType: 'contract',
        },
      ],
      victoryPoints: 0,
      cargo: ['yellow'],
      hasMadeEndGameMove: false,
      hasTimedOut: false,
      timeLeft: 3577083,
      timedOutRound: 0,
    },
  ],
  numberOfCitiesToEmpty: 5,
  board: [
    {
      city: {
        name: 'Newcastle',
        goods: ['black', 'red'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'West',
      },
      column: 0,
      row: 3,
    },
    {
      column: 1,
      row: 2,
    },
    {
      column: 1,
      row: 4,
    },
    {
      column: 1,
      row: 6,
    },
    {
      city: {
        name: 'London',
        goods: ['red', 'red'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'West',
      },
      column: 1,
      row: 8,
    },
    {
      column: 2,
      row: 1,
    },
    {
      column: 2,
      row: 3,
    },
    {
      column: 2,
      row: 5,
    },
    {
      city: {
        name: 'Brügge',
        goods: ['brown', 'brown'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'West',
      },
      column: 2,
      row: 7,
    },
    {
      city: {
        name: 'Bergen',
        goods: ['green', 'green'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'West',
      },
      column: 3,
      row: 0,
    },
    {
      column: 3,
      row: 2,
    },
    {
      column: 3,
      row: 4,
    },
    {
      city: {
        name: 'Hamburg',
        goods: ['green', 'brown'],
        nrContracts: 3,
        contracts: [
          {
            value: 3,
            cargo: ['gray', 'green'],
            region: 'West',
            uuid: 'W_gry_grn_3',
          },
        ],
        coatOfArms: 'fake',
        region: 'West',
      },
      column: 3,
      row: 6,
    },
    {
      column: 4,
      row: 1,
    },
    {
      city: {
        name: 'Tønsberg',
        goods: ['blue'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'Central',
      },
      column: 5,
      row: 0,
    },
    {
      column: 5,
      row: 2,
    },
    {
      column: 5,
      row: 4,
    },
    {
      city: {
        name: 'Lübeck',
        goods: ['yellow', 'yellow'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'Central',
      },
      column: 5,
      row: 6,
    },
    {
      city: {
        name: 'Falsterbo',
        goods: ['black'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'Central',
      },
      column: 6,
      row: 5,
    },
    {
      city: {
        name: 'Stettin',
        goods: ['green', 'yellow'],
        nrContracts: 3,
        contracts: [
          {
            value: 2,
            cargo: ['yellow', 'green'],
            region: 'Central',
            uuid: 'C_yel_grn_2',
          },
          {
            value: 1,
            cargo: ['green', 'blue'],
            region: 'Central',
            uuid: 'C_grn_blu_1',
          },
        ],
        coatOfArms: 'fake',
        region: 'Central',
      },
      column: 6,
      row: 7,
    },
    {
      column: 7,
      row: 4,
    },
    {
      column: 7,
      row: 6,
    },
    {
      city: {
        name: 'Stockholm',
        goods: ['blue', 'brown'],
        nrContracts: 3,
        contracts: [
          {
            value: 5,
            cargo: ['red', 'yellow'],
            region: 'East',
            uuid: 'E_red_yel_5',
          },
          {
            value: 1,
            cargo: ['gray', 'brown'],
            region: 'East',
            uuid: 'E_gry_bro_1',
          },
          {
            value: 2,
            cargo: ['gray', 'green'],
            region: 'East',
            uuid: 'E_gry_grn_2',
          },
        ],
        coatOfArms: 'fake',
        region: 'East',
      },
      column: 8,
      row: 1,
    },
    {
      city: {
        name: 'Visby',
        goods: ['gray', 'black'],
        nrContracts: 4,
        contracts: [
          {
            value: 3,
            cargo: ['red', 'gray'],
            region: 'East',
            uuid: 'E_red_gry_3',
          },
          {
            value: 2,
            cargo: ['brown', 'black'],
            region: 'East',
            uuid: 'E_bro_bla_2',
          },
          {
            value: 3,
            cargo: ['red', 'blue'],
            region: 'East',
            uuid: 'E_red_blu_3',
          },
          {
            value: 2,
            cargo: ['green', 'blue'],
            region: 'East',
            uuid: 'E_grn_blu_2',
          },
        ],
        coatOfArms: 'fake',
        region: 'East',
      },
      column: 8,
      row: 3,
    },
    {
      city: {
        name: 'Danzig',
        goods: ['black', 'brown'],
        nrContracts: 3,
        contracts: [
          {
            value: 1,
            cargo: ['yellow', 'black'],
            region: 'East',
            uuid: 'E_yel_bla_1',
          },
          {
            value: 3,
            cargo: ['yellow', 'green'],
            region: 'East',
            uuid: 'E_yel_grn_3',
          },
          {
            value: 3,
            cargo: ['red', 'black'],
            region: 'East',
            uuid: 'E_red_bla_3',
          },
        ],
        coatOfArms: 'fake',
        region: 'East',
      },
      column: 8,
      row: 5,
    },
    {
      city: {
        name: 'Åbo',
        goods: ['black', 'black'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'East',
      },
      column: 9,
      row: 0,
    },
    {
      column: 9,
      row: 2,
    },
    {
      column: 9,
      row: 4,
    },
    {
      column: 10,
      row: 1,
    },
    {
      city: {
        name: 'Riga',
        goods: ['blue', 'blue'],
        nrContracts: 3,
        contracts: [],
        coatOfArms: 'fake',
        region: 'East',
      },
      column: 10,
      row: 3,
    },
    {
      city: {
        name: 'Reval',
        goods: ['gray', 'gray'],
        nrContracts: 3,
        contracts: [
          {
            value: 3,
            cargo: ['red', 'brown'],
            region: 'East',
            uuid: 'E_red_bro_3',
          },
          {
            value: 2,
            cargo: ['green', 'brown'],
            region: 'East',
            uuid: 'E_grn_bro_2',
          },
          {
            value: 2,
            cargo: ['yellow', 'brown'],
            region: 'East',
            uuid: 'E_yel_bro_2',
          },
        ],
        coatOfArms: 'fake',
        region: 'East',
      },
      column: 11,
      row: 0,
    },
  ],
  achievements: [
    // {
    //   description: 'Four contracts worth 3 VP',
    //   name: 'Banker',
    //   target: 4,
    //   uuid: 'Banker_A_2-5_4P',
    //   value: 4,
    // },
    // {
    //   description: 'Four contracts worth 3 or 5 VP',
    //   name: 'Banker',
    //   target: 4,
    //   uuid: 'Banker_B_2-5_3P',
    //   value: 3,
    // },
    // {
    //   description: 'Six contracts worth 1 VP',
    //   name: 'Merchant',
    //   target: 6,
    //   uuid: 'Merchant_A_2-3_5P',
    //   value: 5,
    // },
    // {
    //   description: 'Seven contracts worth 1 or 2 VP',
    //   name: 'Merchant',
    //   target: 7,
    //   uuid: 'Merchant_B_2-3_4P',
    //   value: 4,
    // },
    {
      description: 'Five contracts worth 1 VP',
      name: 'Merchant',
      target: 5,
      uuid: 'Merchant_A_4-5_5P',
      value: 5,
    },
    {
      description: 'Six contracts worth 1 or 2 VP',
      name: 'Merchant',
      target: 6,
      uuid: 'Merchant_B_4-5_4P',
      value: 4,
    },
    {
      description: 'Cargo in every color',
      name: 'Diversifier',
      target: 7,
      uuid: 'Diversifier_A_2-5_4P',
      value: 4,
    },
    {
      description: 'Two red, yellow and gray cargo',
      name: 'Diversifier',
      target: 6,
      uuid: 'Diversifier_B_2-5_4P',
      value: 4,
    },
    {
      description: 'Three emptied cities',
      name: 'Supplier',
      target: 3,
      uuid: 'Supplier_A_2-3_4P',
      value: 4,
    },
    {
      description: 'Two emptied cities',
      name: 'Supplier',
      target: 2,
      uuid: 'Supplier_B_4-5_3P',
      value: 3,
    },
    // {
    //   description: 'Six contracts with same color',
    //   name: 'Specialist',
    //   target: 6,
    //   uuid: 'Monopolist_A_2-3_4P',
    //   value: 4,
    // },
    // {
    //   description: 'Four green contracts',
    //   name: 'Specialist',
    //   target: 4,
    //   uuid: 'Specialist_B_2-5_4P',
    //   value: 4,
    // },
    // {
    //   description: 'Five contracts with same color',
    //   name: 'Specialist',
    //   target: 5,
    //   uuid: 'Monopolist_B_4-5_3P',
    //   value: 3,
    // },
    {
      description: 'Three blue contracts',
      name: 'Specialist',
      target: 3,
      uuid: 'Specialist_A_2-5_3P',
      value: 3,
    },
    // {
    //   description: 'Two contracts from each region',
    //   name: 'Explorer',
    //   target: 6,
    //   uuid: 'Explorer_A_2-5_4P',
    //   value: 4,
    // },
    // {
    //   description: 'Five Central contracts',
    //   name: 'Explorer',
    //   target: 5,
    //   uuid: 'Regional_A_2-5_5P',
    //   value: 5,
    // },
    // {
    //   description: 'One contract from each region',
    //   name: 'Explorer',
    //   target: 3,
    //   uuid: 'Explorer_B_2-5_3P',
    //   value: 3,
    // },
    // {
    //   description: 'Four Western contracts',
    //   name: 'Explorer',
    //   target: 4,
    //   uuid: 'Regional_B_2-5_3P',
    //   value: 3,
    // },
  ],

  tempo: 3600000,
};

export const MOCK_SESSIONS_ACHIEVEMENTS: ISession[] = [
  {
    user: { name: 'lynden', uuid: '1UiCjICtBFvRPSVb2cTAP', connected: true },
    activeGameUuid: 'iX1JUcNFe5mEQ3igWXdUL',
    // activeGameUuid: 'VJHXkcSEtfpT01yhgNxB0',
    // activeGameUuid: 'T37rB8x5iolLlYmReFZix',
    uuid: 'Tl-3NLoZNVOGGZMNInRz8',
    email: 'iphonelynden@gmail.com',
  },
  {
    user: { name: 'person1', uuid: '4s1zxMT_G5DsCnP5GRk7l', connected: true },
    activeGameUuid: 'iX1JUcNFe5mEQ3igWXdUL',
    // activeGameUuid: 'VJHXkcSEtfpT01yhgNxB0',
    // activeGameUuid: 'T37rB8x5iolLlYmReFZix',
    uuid: 'ul0BTmoadsDeBo1yKysKb',
    email: 'person1@mock.now',
  },
  {
    uuid: 'U8y95tvEFTfnlzC06OT9-',
    user: {
      name: 'Person2',
      uuid: '8YNzwnOSPAAEAwK9bHdYy',
      connected: true,
    },
    activeGameUuid: 'iX1JUcNFe5mEQ3igWXdUL',
    email: 'person2@mock.now',
  },
  {
    user: {
      name: 'Person4',
      uuid: 'v87ki0VQLVv23RCuUZY77',
      connected: true,
    },
    uuid: '_gAqwi8jyyctbxbxAKE9J',
    email: 'person4@mock.now',
    activeGameUuid: 'iX1JUcNFe5mEQ3igWXdUL',
  },
  {
    user: {
      name: 'Person3',
      uuid: 'Vr2LJteMKXN6RAS5Ae8qs',
      connected: true,
    },
    uuid: 'SF9s41WrXTqu6XqTBrfx9',
    email: 'person3@mock.now',
    activeGameUuid: 'iX1JUcNFe5mEQ3igWXdUL',
  },
];

export const MOCK_CHAT_ACHIEVEMENTS: IChat = {
  gameUuid: 'iX1JUcNFe5mEQ3igWXdUL',
  messages: [
    {
      uuid: '0syDyCcqbi9f2Xhnx7PzS',
      from: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been',
    },
    {
      uuid: '78n7n4At3seZJ3DSeHLZy',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been',
    },
    {
      uuid: '2lJeKY38O5Gion6pGPoPr',
      from: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      message:
        'lly unchanged. It was popularised in the 1960s with the release of Letraset sheets conta',
    },
    {
      uuid: 'Gb1Y-IdzB-Y4tvOThwCPV',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'Use setTimeout in your React components to execute a function or block of code after a period of time. Let’s explore ho',
    },
    {
      uuid: '3iAUyNQ6PzLwvBhNvWwSY',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'For example, the code below prints “Hello, World!” to the developer console after 3,000 milliseconds (or 3 seconds).',
    },
    {
      uuid: 'VUrYqPDVC9dV6TJ3Hn0TC',
      from: {
        name: 'person1',
        uuid: '4s1zxMT_G5DsCnP5GRk7l',
        connected: true,
      },
      message:
        'It is a long established fact that a reader will be distracted by the readable content of a pa',
    },
    {
      uuid: 'KAlgBRi7lwqahhbwogvZa',
      from: {
        name: 'lynden',
        uuid: '1UiCjICtBFvRPSVb2cTAP',
        connected: true,
      },
      message:
        'tTimeout inside of the useEffect Hook, which is the equivalent of the componentDidMount lifecycle method in Class components',
    },
  ],
};
